# -*- coding: utf-8 -*-
"""
Created on Wed Oct 27 15:14:51 2021

@author: emmanuel.amador@edf.fr
"""

from bs4 import BeautifulSoup
import requests
import lxml
import pandas as pd
import json

#proxies = {
#  "http": "http://proxy.proxy.com:3131",
#  "https": "http://proxy.proxy.com:3131",
#}
s = requests.Session()
#s.proxies = proxies


urls=[r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Ain',
      r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Belley',
      r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Bourg-en-Bresse',
      r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_P%C3%A9rouges',
      r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Tr%C3%A9voux',
      r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Aisne',
      r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Aisne_(nord)',
      r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Aisne_(sud)',
      r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Ch%C3%A2teau-Thierry',
      r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Laon',
      r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Soissons',
      r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Allier',
      r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Allier_(hors_Montluçon,_Moulins_et_Vichy)',
      r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Moulins',
      r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Montlu%C3%A7on',
      r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Vichy',
      r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_des_Alpes-de-Haute-Provence',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_des_Hautes-Alpes',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Brian%C3%A7on',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Embrun',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_des_Alpes-Maritimes',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Nice',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Grasse',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Cannes',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Ard%C3%A8che',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Bourg-Saint-And%C3%A9ol',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_des_Ardennes',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Charleville-M%C3%A9zi%C3%A8res',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Ari%C3%A8ge',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Mirepoix',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Aube',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Troyes',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Aude',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Alet-les-Bains',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Carcassonne',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Narbonne',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Aveyron',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Rodez',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Villefranche-de-Rouergue',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_des_Bouches-du-Rh%C3%B4ne',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Aix-en-Provence',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Arles',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_des_Baux-de-Provence',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Fontvieille',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Marseille',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Tarascon',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Calvados',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Bayeux',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Caen',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Lisieux',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Vire',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Caen',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Bayeux',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Falaise',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Honfleur',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Lisieux',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Pont-l%27%C3%89v%C3%AAque_(Calvados)',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Calvados_(A-F)',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Calvados_(G-O)',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Calvados_(P-Z)',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Cantal',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Aurillac',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Saint-Flour',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Charente',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Angoul%C3%AAme',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Cognac',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Confolens',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Charente-Maritime',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Charente-Maritime_(A-N)',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Charente-Maritime_(O-Z)',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27%C3%8Ele-d%27Aix',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_La_Rochelle',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Saintes',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Cher',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Bourges',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Corr%C3%A8ze',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Brive-la-Gaillarde',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Collonges-la-Rouge',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_C%C3%B4te-d%27Or',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Beaune',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Dijon',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Ch%C3%A2tillon-sur-Seine',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_C%C3%B4te-d%27Or_(A-L)',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_C%C3%B4te-d%27Or_(M-Z)',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_des_C%C3%B4tes-d%27Armor',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Dinan',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Lannion',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Saint-Brieuc',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Tr%C3%A9guier',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_des_C%C3%B4tes-d%27Armor_(A-O)',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_des_C%C3%B4tes-d%27Armor_(P-Z)',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Creuse',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Dordogne',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Bergerac',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Nontron',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_P%C3%A9rigueux',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Sarlat-la-Can%C3%A9da',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_des_Eyzies-de-Tayac-Sireuil',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Monpazier',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_P%C3%A9rigueux',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Sarlat-la-Can%C3%A9da',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Doubs',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Besan%C3%A7on',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Montb%C3%A9liard',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Dr%C3%B4me',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Eure',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Eure_(A-I)',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Eure_(J-Z)',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Eure-et-Loir',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Chartres',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Ch%C3%A2teaudun',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Finist%C3%A8re',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Faou',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Landerneau',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Locronan',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Morlaix',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Penmarc%27h',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Quimper',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Quimperl%C3%A9',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Saint-Pol-de-L%C3%A9on',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Finist%C3%A8re_(A-O)',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Finist%C3%A8re_(P-Z)',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Corse-du-Sud',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Haute-Corse',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Bastia',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Gard',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Beaucaire',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_N%C3%AEmes',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Uz%C3%A8s',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Villeneuve-l%C3%A8s-Avignon',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Haute-Garonne',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Haute-Garonne_(A-L)',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Haute-Garonne_(M-Z)',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Toulouse',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Gers',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Auch',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Gironde',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Bordeaux',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Saint-%C3%89milion',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_d%27Arcachon',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Blaye',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Bordeaux',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Langon',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Lesparre-M%C3%A9doc',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Libourne',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27H%C3%A9rault',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Hérault_(A-L)',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27H%C3%A9rault_(M-Z)',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_B%C3%A9ziers',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Montpellier',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_P%C3%A9zenas',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Ille-et-Vilaine',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Foug%C3%A8res',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Rennes',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Saint-Malo',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Vitr%C3%A9',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Indre',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Indre-et-Loire',
          r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Amboise',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Chinon',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Loches',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Richelieu',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Tours',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Indre-et-Loire_(A-J)',
        r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Indre-et-Loire_(K-Z)',
      r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Is%C3%A8re',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Cr%C3%A9mieu',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Grenoble',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_La_C%C3%B4te-Saint-Andr%C3%A9',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Vienne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_d%C3%A9partement_du_Jura',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Arbois',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Dole',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Lons-le-Saunier',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Poligny_(Jura)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Salins-les-Bains',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_des_Landes',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Loir-et-Cher',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Blois',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Vend%C3%B4me',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Loire',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Saint-%C3%89tienne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Montbrison',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Haute-Loire',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Haute-Loire_(ouest)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Haute-Loire_(est)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Puy-en-Velay',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Loire-Atlantique',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Nantes',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Loiret',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Orl%C3%A9ans',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Lot',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Lot_(A-K)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Lot_(L-Z)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Cahors',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Figeac',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Rocamadour',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Lot-et-Garonne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Lot-et-Garonne_(A-L)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Lot-et-Garonne_(M-Z)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Agen',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Loz%C3%A8re',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Mende',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Maine-et-Loire',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Angers',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Saumur',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Maine-et-Loire_(nord)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Maine-et-Loire_(sud)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Manche',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Saint-L%C3%B4',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Coutances',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Cherbourg',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_d%27Avranches',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Marne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Ch%C3%A2lons-en-Champagne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Reims',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Haute-Marne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Chaumont',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Langres',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Mayenne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Laval',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Meurthe-et-Moselle',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Nancy',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Pont-%C3%A0-Mousson',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Toul',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Meuse',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Bar-le-Duc',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Verdun',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Morbihan',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Lorient',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Pontivy',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Vannes',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Auray',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Carnac',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Plo%C3%ABrmel',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Vannes',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Moselle',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Metz',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Phalsbourg',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Thionville',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Ni%C3%A8vre',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Nevers',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Nord',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Cambrai',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Douai',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Dunkerque',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_m%C3%A9tropole_europ%C3%A9enne_de_Lille',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Lille',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Roubaix',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Tourcoing',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Villeneuve-d%27Ascq',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Valenciennes',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Oise',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Oise_(ouest)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Oise_(est)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Beauvais',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Compi%C3%A8gne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Senlis',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Orne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Mortagne-au-Perche',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Alen%C3%A7on',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Pas-de-Calais',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Pas-de-Calais_(A-H)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Pas-de-Calais_(I-Z)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Puy-de-D%C3%B4me',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Puy-de-D%C3%B4me_(A-L)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Puy-de-D%C3%B4me_(M-Z)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Billom',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Clermont-Ferrand',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Riom',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Thiers',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_des_Pyr%C3%A9n%C3%A9es-Atlantiques',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_des_Pyr%C3%A9n%C3%A9es-Atlantiques_(A-L)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_des_Pyr%C3%A9n%C3%A9es-Atlantiques_(M-Z)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Bayonne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_des_Hautes-Pyr%C3%A9n%C3%A9es',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_des_Pyr%C3%A9n%C3%A9es-Orientales',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Perpignan',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Villefranche-de-Conflent',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Bas-Rhin',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Bas-Rhin_(A-L)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Bas-Rhin_(M-Z)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Benfeld',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_B%C5%93rsch',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Bouxwiller_(Bas-Rhin)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Dambach-la-Ville',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Haguenau',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Molsheim',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Neuwiller-l%C3%A8s-Saverne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Obernai',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Rosheim',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Sarre-Union',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Saverne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Scherwiller',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_S%C3%A9lestat',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Strasbourg',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Westhoffen',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Wissembourg',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Haut-Rhin',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Ammerschwihr',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Bergheim',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Colmar',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Ensisheim',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Guebwiller',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Kaysersberg',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Masevaux',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Mulhouse',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Neuf-Brisach',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Ribeauvill%C3%A9',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Riquewihr',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Rouffach',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Sainte-Marie-aux-Mines',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Thann',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Turckheim',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Rh%C3%B4ne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Villefranche-sur-Sa%C3%B4ne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_m%C3%A9tropole_de_Lyon',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Lyon',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Haute-Sa%C3%B4ne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Vesoul',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Gray',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Haute-Sa%C3%B4ne_(Vesoul_-_Gray)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Haute-Sa%C3%B4ne_(Lure_-_H%C3%A9ricourt)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Haute-Sa%C3%B4ne_(Luxeuil_-_Jussey)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Sa%C3%B4ne-et-Loire',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Sa%C3%B4ne-et-Loire_(A-L)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Sa%C3%B4ne-et-Loire_(M-Z)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Autun',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Chalon-sur-Sa%C3%B4ne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Cluny',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_M%C3%A2con',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Tournus',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Sarthe',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Mans',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_du_Mans',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_La_Fl%C3%A8che',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Mamers',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Savoie',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Chamb%C3%A9ry',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Haute-Savoie',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Annecy',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_1er_arrondissement_de_Paris',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_2e_arrondissement_de_Paris',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_3e_arrondissement_de_Paris',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_4e_arrondissement_de_Paris',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_5e_arrondissement_de_Paris',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_6e_arrondissement_de_Paris',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_7e_arrondissement_de_Paris',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_8e_arrondissement_de_Paris',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_9e_arrondissement_de_Paris',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_10e_arrondissement_de_Paris',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_11e_arrondissement_de_Paris',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_12e_arrondissement_de_Paris',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_13e_arrondissement_de_Paris',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_14e_arrondissement_de_Paris',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_15e_arrondissement_de_Paris',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_16e_arrondissement_de_Paris',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_17e_arrondissement_de_Paris',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_18e_arrondissement_de_Paris',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_19e_arrondissement_de_Paris',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_20e_arrondissement_de_Paris',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Seine-Maritime',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Dieppe',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_du_Havre',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27arrondissement_de_Rouen',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Dieppe',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Havre',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Rouen',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Seine-et-Marne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Seine-et-Marne_(ouest)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Seine-et-Marne_(est)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Fontainebleau',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Provins',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_des_Yvelines',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_des_Yvelines_(nord)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_des_Yvelines_(sud)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Saint-Germain-en-Laye',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Versailles',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_des_Deux-S%C3%A8vres',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Niort',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Somme',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Amiens',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Abbeville',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Tarn',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Albi',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Cordes-sur-Ciel',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Tarn-et-Garonne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Auvillar',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Montauban',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Var',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Toulon',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Hy%C3%A8res',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Fr%C3%A9jus',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Vaucluse',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Apt',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Avignon',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Carpentras',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Cavaillon',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Pernes-les-Fontaines',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Vend%C3%A9e',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Fontenay-le-Comte',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27%C3%8Ele_d%27Yeu',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_La_Roche-sur-Yon',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Noirmoutier-en-l%27%C3%AEle',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Vienne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Poitiers',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Vienne_(A-L)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Vienne_(M-Z)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Haute-Vienne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Limoges',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_d%C3%A9partement_des_Vosges',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27%C3%89pinal',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Neufch%C3%A2teau',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Saint-Di%C3%A9-des-Vosges',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Yonne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_d%27Auxerre',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Joigny',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Sens',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Tonnerre',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Yonne_(A-M)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Yonne_(N-Z)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Territoire_de_Belfort',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_l%27Essonne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_des_Hauts-de-Seine',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Seine-Saint-Denis',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Val-de-Marne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_du_Val-d%27Oise',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Guadeloupe',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Martinique',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Fort-de-France',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Saint-Pierre_(Martinique)',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_la_Guyane',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Cayenne',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_La_R%C3%A9union',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Saint-Pierre-et-Miquelon',
r'https://fr.wikipedia.org/wiki/Liste_des_monuments_historiques_de_Mayotte']

geojson={"type": "FeatureCollection","features": []}

colonnes=[]
for u in urls:
    #print(u)
    table_class="wikitable sortable jquery-tablesorter"
    response=s.get(u)
    #print(response.status_code)
    # parse data from the html into a beautifulsoup object
    soup = BeautifulSoup(response.text, 'html.parser')
    monumenttables=soup.find_all('table',{'class':"wikitable"})
    for table in monumenttables:
        df=pd.read_html(str(table))
        # convert list to dataframe
        df=pd.DataFrame(df[0])
        cols=list(df.columns)
        # if cols not in colonnes:
        #     print(cols)
        #     colonnes.append(cols)
        for tr in table.find_all('tr'):
            tds = tr.find_all('td')
            try:
                commune=''
                notice=''
                adresse=''
                nom=tds[0].text.strip()
                classement=''
                for i in range(len(cols)):
                    if 'COMMUNE' in cols[i].upper():
                        commune=tds[i].text.strip()
                    if 'www.pop.culture.gouv.fr/notice/merimee' in str(tds[i].find('a')):
                        for j in str(tds[i].find('a')).split('"'):
                            if 'www.pop.culture.gouv.fr' in j:
                                url=j
                                num=j.split('/')[-1]
                                notice='<a href="'+url+'" target="_blank">'+num+' </a>'
                                break
                    if 'ADRESSE' in cols[i].upper():
                        adresse=tds[i].text.strip()
                    if 'PROTECTION' in cols[i].upper() or 'CLASSEMENT' in cols[i].upper() :
                        if 'PA' not in tds[i].text.strip():
                            classement=tds[i].text.strip()
                            if 'CLASS' in classement.upper() and 'INSCR' in classement.upper():
                                classement='Classé'
                            if 'INSCR' in classement.upper() and 'CLASS' not in classement.upper():
                                classement='Inscrit'
                            if 'CLASS' in classement.upper() and 'INSCR' not in classement.upper():
                                classement='Classé'
                        else:
                            for i in range(len(cols)):
                                if 'CLASS' in tds[i].text.strip().upper() and 'INSCR' in tds[i].text.strip().upper():
                                    classement=tds[i].text.strip()
                                    if 'CLASS' in classement.upper() and 'INSCR' in classement.upper():
                                        classement='Classé'
                                    if 'INSCR' in classement.upper() and 'CLASS' not in classement.upper():
                                        classement='Inscrit'
                                    if 'CLASS' in classement.upper() and 'INSCR' not in classement.upper():
                                        classement='Classé'
                            
                lat=float(str(tds).split('Map')[1].split('/fr')[0].split('/')[2])
                lon=float(str(tds).split('Map')[1].split('/fr')[0].split('/')[3])

                feat={"type": "Feature","geometry": {"type": "Point", "coordinates": [lon, lat]},"properties": {'Nom':nom,'Commune':commune,'Adresse':adresse,'Notice':notice,'Classement':classement}}
                if feat not in geojson["features"]:
                    geojson["features"].append(feat)
            except:
                pass
    print(u.split('/')[-1]+5*'\t'+str(len(geojson["features"]))+' monuments au total')

with open("monumentshistoriques.geojson", "w") as outfile:
    json.dump(geojson, outfile)
